name: Build Vote

on:
  push:
    branches:
      - main
    paths:
      - 'vote/**'
      - '.github/workflows/build-vote.yaml'
  pull_request:
    paths:
      - 'vote/**'
      - '.github/workflows/build-vote.yaml'

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v4.1.1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: szymonpapuga/example-voting-app-vote:latest,szymonpapuga/example-voting-app-vote:01
          context: vote
          cache-from: type=gha
          cache-to: type=gha,mode=max
