name: Build Worker

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**'
      - '.github/workflows/build-worker.yaml'
  pull_request:
    paths:
      - 'worker/**'
      - '.github/workflows/build-worker.yaml'

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v4.1.1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: szymonpapuga/example-voting-app-worker:latest,szymonpapuga/example-voting-app-worker:01
          context: worker
