name: Build Worker

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**'
      - '.github/workflows/build-worker.yaml'
  pull_request:
    paths:
      - 'worker/**'
      - '.github/workflows/build-worker.yaml'

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.8.0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v4.1.1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: szymonpapuga/example-voting-app-worker:latest,szymonpapuga/example-voting-app-worker:01
          context: "{{defaultContext}}:worker"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7
